BlogMvc/Models/AppModels/Article.cs
using BlogMvc.Library;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;

namespace BlogMvc.Models.AppModels
{
    public class Article : BaseEntity
    {
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }

    }
}

BlogMvc/ViewModels/ArticlesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogMvc.ViewModels
{
    public class ArticlesViewModel
    {
    }
}

BlogMvc/Areas/Articles/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogMvc.Library;
using BlogMvc.Models.AppModels;
using BlogMvc.Services;

namespace BlogMvc.Areas.Articles.Controllers
{
    public class ArticleController : FrontController
    {
        private ArticleService _service = null;
        public ArticleController(ArticleService service)
        {
            _service = service;
        }

        // GET: Article
        public async Task<ActionResult> Index()
        {
            return View(await _service.GetAllAsync());
        }

        // GET: Article/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = await _service.FindAsync((int)id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Article/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Article/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Title,SubTitle,Content,Author,Description")] Article article)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(article);
                return RedirectToAction("Index");
            }

            return View(article);
        }

        // GET: Article/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = await _service.FindAsync((int)id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Article/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Title,SubTitle,Content,Author,Description")] Article article)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(article);
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Article/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = await _service.FindAsync((int)id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Article/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Article article = await _service.FindAsync(id);
            await _service.RemoveAsync(article);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Test()
        {

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _service.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogMvc/Areas/Articles/Views/Article/Create.cshtml
@model BlogMvc.Models.AppModels.Article

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogMvc/Areas/Articles/Views/Article/Delete.cshtml
@model BlogMvc.Models.AppModels.Article

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BlogMvc/Areas/Articles/Views/Article/Details.cshtml
@model BlogMvc.Models.AppModels.Article

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BlogMvc/Areas/Articles/Views/Article/Edit.cshtml
@model BlogMvc.Models.AppModels.Article

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogMvc/Areas/Articles/Views/Article/Index.cshtml
@model IEnumerable<BlogMvc.Models.AppModels.Article>
@using BlogMvc.Models.AppModels

@{
    ViewBag.Title = "Index";
}

<hr />

@using (Html.UI().BeginRowBox("row text-left"))
{
    using (Html.UI().BeginColumn(3))
    {
        @Html.ActionLink("Nowy artykuł", "Create", "Article", new { Area = "Articles" }, null)
    }

}


@(Html.UI().Table(Model)
    .Column(c => c.ID)
    .Column(c => c.Content, "Treść")
    .Column(c => c.CreatedBy)
    .Column(c => c.CreatedOn, "Utworzone")
    .Column(c => c.Description)
    .Column(c => c.ModifiedBy, "Zmodyfikowane przez")
    .Column(c => c.ModifiedOn)
    .Column(c => c.SubTitle, "Krótki opis")
    .Column(c => c.Title, "Tytuł")
)
<hr />
@Html.UI().SpanText("Kornelia")
<hr />

@using (Html.UI().BeginRowBox("row text-center", "rowid"))
{
    using (Html.UI().BeginColumn(3))
    {
        <div>
            @Html.UI().SpanText("Kordelia")
        </div>
    }
    using (Html.UI().BeginColumn(3))
    {
        <div>
            @Html.UI().SpanText("Kornelia")
        </div>
    }
    using (Html.UI().BeginColumn(3))
    {
        <div>
            @Html.UI().SpanText("Kamila")
        </div>
    }

    using (Html.UI().BeginColumn(3))
    {
        using (Html.UI().BeginLink("http://google.pl", "linkid", null, true))
        {
            @Html.UI().SpanText("Wewnatrz linka")
        }
    }
}

<hr />

BlogMvc/Areas/Articles/Views/Article/Test.cshtml
@{
    ViewBag.Title = "Test";
}

@using (Html.UI().BeginContainer(null, null, "color:red;font-size:10px;"))
{
    using (Html.UI().BeginRowBox())
    {
        using (Html.UI().BeginColumn(4))
        {
            using (Html.UI().BeginBox(null, "internal"))
            {
                @Html.UI().Link("http://www.google.pl", "Link do Google", null, null, true)
            }
        }

        using (Html.UI().BeginColumn(4))
        {
            using (Html.UI().BeginBox(null, "internal"))
            {
                using (Html.UI().BeginLink("#"))
                {
                    <text>Przykładowy tekst</text>
                }
            }
        }

        using (Html.UI().BeginColumn(4))
        {
            using (Html.UI().BeginBox("second", "internal"))
            {
                using (Html.UI().BeginBox())
                {
                    <p>Tekst w div</p>
                }
            }
        }
    }
}